version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=admin
    ports:
      - "15432:5432"
  api:
    build: ./backend/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3010 -b '0.0.0.0'"
    image: api
    volumes:
      - ./backend:/backend
    environment:
      RAILS_ENV: development
    ports:
      - "3010:3010"
    depends_on:
      - db
  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/frontend
    ports:
      - "3000:3000"
